<a href="https://colab.research.google.com/github/kainat25/DSA-pr--20SW061/blob/main/Lab4_20SW061.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK1

In [7]:
import numpy as np
X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


TASK 2


In [8]:
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print(X)
print(Y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


TASK 3

In [9]:
import numpy as np
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


TASK 4

In [10]:
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 1.66749049  0.97800401 -0.85309509 ...  0.37858139 -1.73067943
  -0.71742101]
 [ 0.61590322 -0.16302138 -0.32176229 ... -1.39705836 -0.43487904
  -0.6095008 ]
 [ 0.52705624 -1.11480695 -0.69977166 ... -0.75725016  0.95573601
  -0.54931454]
 ...
 [ 1.2107615  -0.65951407  0.18696061 ...  0.0524856   0.584203
  -1.25978922]
 [ 0.7581972   0.38724056  0.4144728  ...  0.12816184 -0.55778694
   0.79346186]
 [-0.79246021 -1.38504981 -0.17833069 ...  0.44187425  0.98453158
  -1.30268058]]
Average of all values in X_norm: -1.5631940186722205e-17
Average of minimum values in each column of X_norm: -1.7303669199019283
Average of maximum values in each column of X_norm: 1.7410325171010648
Random permutation of row indices: [497 747 877 905 154 220 762  14 378 494 104 123  31 857 702 202 850 266
 208 729 771 401 700 227 119 912 128 199 556 415 336 655  21   1 863 409
 817 287 684 318  12 790 